#!/bin/sh

# Network traffic monitoring script.
# Stores how much data has been received (RX) or transmitted (TX) by reading
# system statistics.
# Notifies delta RX and delta TX since the previous time the cache was updated.
#
# If 'network-traffic -u' is run every hour, 'network-traffic -n' will show
# network traffic per hour.

device="wlp3s0"
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/netlog"
prevdata="$(cat "$logfile")"

rxcurrent="$(($(paste -d '+' /sys/class/net/$device/statistics/rx_bytes)))"
txcurrent="$(($(paste -d '+' /sys/class/net/$device/statistics/tx_bytes)))"

update_cache() {
    touch $logfile
    truncate --size=0 $logfile
    echo "$rxcurrent $txcurrent" > "$logfile"
}

notify() {
    notify-send "Network traffic update" \
    "$(printf "Device: wlp3s0\n\nReceived: %sKiB\nTransmitted: %sKiB\\n" \
	"$(((rxcurrent-${prevdata%% *})/1024))" \
    "$(((txcurrent-${prevdata##* })/1024))")"
}

case "$1" in
	-n*) notify ;;
	-u*) update_cache;;
	*) printf "Usage: network-traffic [OPTION]\\n\\t-n: notify network traffic since last cache update.\\n\\t-u: update network traffic cache.\n" ;;
esac
