#!/bin/bash
# Hosts file update script
# R. Nicolás Savinelli [27/Aug/2019]

# URL to StevenBlack/hosts hosts file
# For more information on which hosts file to use visit:
# https://github.com/StevenBlack/hosts
hosts_file="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts"
hosts_temp=$(mktemp)

# Makes sure only root can run the script
if [ $(id -u) -ne 0 ]; then
	echo "WARNING: This script must be run as root." 1>&2
	exit 1

else
	echo -e "Downloading updated hosts file:\n"
	wget --progress=dot:binary --output-document=$hosts_temp $hosts_file

	# Checks wget's exit value
	if [ $? -ne 0 ]; then
		echo -e "WARNING: Download failed.\nNo changes were made." 1>&2
		exit 1

	else
		echo "Creating /etc/hosts.backup file..."
		mv -u /etc/hosts /etc/hosts.backup
		echo "Adding custom host records to the new hosts file..."
        sed -i "/# Custom host records are listed here/ a 127.0.1.1 $(hostname)" $hosts_temp
		echo "Custom host records were added."
		echo "Updating old configuration..."
		mv -u $hosts_temp /etc/hosts
		echo "/etc/hosts file has been updated."
	fi

fi
